### ISSUE TITLE
Implement `--host` to listeng on specific IP

### ISSUE THREAD

**Issue by JuanuMusic** [invoke-ai/invoke-training#107]
Just like invokeai has the `--host` parameter to define the IP to listen on, it would be nice to add this to the invoke-training project to able to listen from all ips (such as `0.0.0.0`)

I have tried using `--host` when running it but it only listens on 127.0.0.1

**Comment by RyanJDick** [comment]
I added `--host` and `--port` args in https://github.com/invoke-ai/invoke-training/pull/115, so this should be possible now. Let me know if you run into issues with it.
