### ISSUE TITLE
Virtual Environment not activating/creating

### ISSUE THREAD

**Issue by FormerTwitterEmployee** [invoke-ai/invoke-training#121]
Following the instructions from the installation page since I am a luddite. I was able to get the files properly but the other commands don't seem to be working as intended. Creating the virtual environment (step 2) doesn't seem to do anything. And then the activation command is not found.

> * MINGW64 /e/InvokeAI/InvokeAI Training
> $ git clone https://github.com/invoke-ai/invoke-training.git
> Cloning into 'invoke-training'...
> remote: Enumerating objects: 7886, done.
> remote: Counting objects: 100% (2895/2895), done.
> remote: Compressing objects: 100% (1002/1002), done.
> remote: Total 7886 (delta 1753), reused 2626 (delta 1622), pack-reused 4991
> Receiving objects: 100% (7886/7886), 56.44 MiB | 35.88 MiB/s, done.
> Resolving deltas: 100% (4650/4650), done.
> 
> * MINGW64 /e/InvokeAI/InvokeAI Training
> $ cd invoke-training
> 
> * MINGW64 /e/InvokeAI/InvokeAI Training/invoke-training (main)
> $ python -m venv invoketraining
> 
> * MINGW64 /e/InvokeAI/InvokeAI Training/invoke-training (main)
> $ python -m venv invoketraining
> 
> * MINGW64 /e/InvokeAI/InvokeAI Training/invoke-training (main)
> $ .\invoketraining\Scripts\activate
> bash: .invoketrainingScriptsactivate: command not found

**Comment by FormerTwitterEmployee** [comment]
$ python -V
Python 3.10.11

**Comment by RyanJDick** [comment]
You can find full instructions for setting up a venv here: https://docs.python.org/3/library/venv.html

Is the 'activate' script present at that path? The command to activate the venv may differ slightly depending on what shell you are using. See the table here: https://docs.python.org/3/library/venv.html#how-venvs-work

**Comment by FormerTwitterEmployee** [comment]
Thanks for your help!
