### ISSUE TITLE
Mask Dataset Management

### ISSUE THREAD

**Issue by hipsterusername** [invoke-ai/invoke-training#131]
After creating a new dataset, and attempting to add images, receiving a validation error due to missing mask path:

error
1 validation error for ImageCaptionExample mask_path Field required [type=missing, input_value={'image_path': 'C:\\Users...244.jpg', 'caption': ''}, input_type=dict] For further information visit https://errors.pydantic.dev/2.5/v/missing

**Comment by RyanJDick** [comment]
Fixed by https://github.com/invoke-ai/invoke-training/pull/140
