### ISSUE TITLE
Batch file to start training

### ISSUE THREAD

**Issue by FormerTwitterEmployee** [invoke-ai/invoke-training#135]
If anyone is having trouble starting the training, use this file.

- Place it in your invoke-training folder.

- Change the file extension to .bat.

- Run the batch file.

- Profit.

[invoke-training-ui.txt](https://github.com/invoke-ai/invoke-training/files/15476917/invoke-training-ui.txt)

**Comment by hipsterusername** [comment]
Not a bad idea to put a simple bat together - want to make a commit? :)
